name: Terraform CI/CD Pipeline for QA

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Terraform CI/CD Pipeline for QA'
        required: true
        type: string
        default: 'qa'  # Only QA environment

env:
  TF_LOG: DEBUG  # Enable detailed Terraform logging
  ACTIONS_RUNNER_DEBUG: "true"  # Enable runner debug logging
  ACTIONS_STEP_DEBUG: "true"  # Enable step debug logging
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  # CI Job
  terraform-ci:
    name: Terraform CI
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}  # Terraform Cloud API token

      # Step 3: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 4: Plan Terraform Changes for QA environment
      - name: Terraform Plan
        # run: terraform plan -var "environment=qa"
        run: terraform plan

  # CD Job
  terraform-cd:
    name: Terraform CD
    runs-on: ubuntu-latest
    needs: terraform-ci  # CD job depends on the successful completion of the CI job

    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Step 3: Set AWS Credentials for QA environment
      - name: Set AWS Credentials for QA
        run: |
          echo "Setting AWS credentials for QA environment"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_QA }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_QA }}" >> $GITHUB_ENV

      # Step 4: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 5: Apply Terraform Changes for QA environment
      - name: Terraform Apply
        # run: terraform apply -auto-approve -var "environment=qa"
        run: terraform apply -auto-approve
